/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.harmony.tables.Lists;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListsRecord extends UpdatableRecordImpl<ListsRecord> implements Record6<Integer, Integer, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.lists.listid</code>.
     */
    public ListsRecord setListid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.lists.listid</code>.
     */
    public Integer getListid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.lists.userid</code>.
     */
    public ListsRecord setUserid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.lists.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.lists.listName</code>.
     */
    public ListsRecord setListname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.lists.listName</code>.
     */
    public String getListname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>harmony.lists.icon</code>.
     */
    public ListsRecord setIcon(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.lists.icon</code>.
     */
    public String getIcon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>harmony.lists.creationDate</code>.
     */
    public ListsRecord setCreationdate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>harmony.lists.creationDate</code>.
     */
    public LocalDateTime getCreationdate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>harmony.lists.modificationDate</code>.
     */
    public ListsRecord setModificationdate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>harmony.lists.modificationDate</code>.
     */
    public LocalDateTime getModificationdate() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Lists.LISTS.LISTID;
    }

    @Override
    public Field<Integer> field2() {
        return Lists.LISTS.USERID;
    }

    @Override
    public Field<String> field3() {
        return Lists.LISTS.LISTNAME;
    }

    @Override
    public Field<String> field4() {
        return Lists.LISTS.ICON;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Lists.LISTS.CREATIONDATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Lists.LISTS.MODIFICATIONDATE;
    }

    @Override
    public Integer component1() {
        return getListid();
    }

    @Override
    public Integer component2() {
        return getUserid();
    }

    @Override
    public String component3() {
        return getListname();
    }

    @Override
    public String component4() {
        return getIcon();
    }

    @Override
    public LocalDateTime component5() {
        return getCreationdate();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationdate();
    }

    @Override
    public Integer value1() {
        return getListid();
    }

    @Override
    public Integer value2() {
        return getUserid();
    }

    @Override
    public String value3() {
        return getListname();
    }

    @Override
    public String value4() {
        return getIcon();
    }

    @Override
    public LocalDateTime value5() {
        return getCreationdate();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationdate();
    }

    @Override
    public ListsRecord value1(Integer value) {
        setListid(value);
        return this;
    }

    @Override
    public ListsRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public ListsRecord value3(String value) {
        setListname(value);
        return this;
    }

    @Override
    public ListsRecord value4(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public ListsRecord value5(LocalDateTime value) {
        setCreationdate(value);
        return this;
    }

    @Override
    public ListsRecord value6(LocalDateTime value) {
        setModificationdate(value);
        return this;
    }

    @Override
    public ListsRecord values(Integer value1, Integer value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListsRecord
     */
    public ListsRecord() {
        super(Lists.LISTS);
    }

    /**
     * Create a detached, initialised ListsRecord
     */
    public ListsRecord(Integer listid, Integer userid, String listname, String icon, LocalDateTime creationdate, LocalDateTime modificationdate) {
        super(Lists.LISTS);

        setListid(listid);
        setUserid(userid);
        setListname(listname);
        setIcon(icon);
        setCreationdate(creationdate);
        setModificationdate(modificationdate);
    }
}
