/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.harmony.tables.Listmedia;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListmediaRecord extends UpdatableRecordImpl<ListmediaRecord> implements Record4<Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.listmedia.elementid</code>.
     */
    public ListmediaRecord setElementid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.listmedia.elementid</code>.
     */
    public Integer getElementid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.listmedia.listid</code>.
     */
    public ListmediaRecord setListid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.listmedia.listid</code>.
     */
    public Integer getListid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.listmedia.mediaid</code>.
     */
    public ListmediaRecord setMediaid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.listmedia.mediaid</code>.
     */
    public Integer getMediaid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>harmony.listmedia.addedDate</code>.
     */
    public ListmediaRecord setAddeddate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.listmedia.addedDate</code>.
     */
    public LocalDateTime getAddeddate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Listmedia.LISTMEDIA.ELEMENTID;
    }

    @Override
    public Field<Integer> field2() {
        return Listmedia.LISTMEDIA.LISTID;
    }

    @Override
    public Field<Integer> field3() {
        return Listmedia.LISTMEDIA.MEDIAID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Listmedia.LISTMEDIA.ADDEDDATE;
    }

    @Override
    public Integer component1() {
        return getElementid();
    }

    @Override
    public Integer component2() {
        return getListid();
    }

    @Override
    public Integer component3() {
        return getMediaid();
    }

    @Override
    public LocalDateTime component4() {
        return getAddeddate();
    }

    @Override
    public Integer value1() {
        return getElementid();
    }

    @Override
    public Integer value2() {
        return getListid();
    }

    @Override
    public Integer value3() {
        return getMediaid();
    }

    @Override
    public LocalDateTime value4() {
        return getAddeddate();
    }

    @Override
    public ListmediaRecord value1(Integer value) {
        setElementid(value);
        return this;
    }

    @Override
    public ListmediaRecord value2(Integer value) {
        setListid(value);
        return this;
    }

    @Override
    public ListmediaRecord value3(Integer value) {
        setMediaid(value);
        return this;
    }

    @Override
    public ListmediaRecord value4(LocalDateTime value) {
        setAddeddate(value);
        return this;
    }

    @Override
    public ListmediaRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListmediaRecord
     */
    public ListmediaRecord() {
        super(Listmedia.LISTMEDIA);
    }

    /**
     * Create a detached, initialised ListmediaRecord
     */
    public ListmediaRecord(Integer elementid, Integer listid, Integer mediaid, LocalDateTime addeddate) {
        super(Listmedia.LISTMEDIA);

        setElementid(elementid);
        setListid(listid);
        setMediaid(mediaid);
        setAddeddate(addeddate);
    }
}
