/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.harmony.tables.Reports;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportsRecord extends UpdatableRecordImpl<ReportsRecord> implements Record5<Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.reports.reportid</code>.
     */
    public ReportsRecord setReportid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.reports.reportid</code>.
     */
    public Integer getReportid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.reports.useridreporter</code>.
     */
    public ReportsRecord setUseridreporter(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.reports.useridreporter</code>.
     */
    public Integer getUseridreporter() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.reports.useridreported</code>.
     */
    public ReportsRecord setUseridreported(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.reports.useridreported</code>.
     */
    public Integer getUseridreported() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>harmony.reports.reviewid</code>.
     */
    public ReportsRecord setReviewid(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.reports.reviewid</code>.
     */
    public Integer getReviewid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>harmony.reports.reason</code>.
     */
    public ReportsRecord setReason(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>harmony.reports.reason</code>.
     */
    public String getReason() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Reports.REPORTS.REPORTID;
    }

    @Override
    public Field<Integer> field2() {
        return Reports.REPORTS.USERIDREPORTER;
    }

    @Override
    public Field<Integer> field3() {
        return Reports.REPORTS.USERIDREPORTED;
    }

    @Override
    public Field<Integer> field4() {
        return Reports.REPORTS.REVIEWID;
    }

    @Override
    public Field<String> field5() {
        return Reports.REPORTS.REASON;
    }

    @Override
    public Integer component1() {
        return getReportid();
    }

    @Override
    public Integer component2() {
        return getUseridreporter();
    }

    @Override
    public Integer component3() {
        return getUseridreported();
    }

    @Override
    public Integer component4() {
        return getReviewid();
    }

    @Override
    public String component5() {
        return getReason();
    }

    @Override
    public Integer value1() {
        return getReportid();
    }

    @Override
    public Integer value2() {
        return getUseridreporter();
    }

    @Override
    public Integer value3() {
        return getUseridreported();
    }

    @Override
    public Integer value4() {
        return getReviewid();
    }

    @Override
    public String value5() {
        return getReason();
    }

    @Override
    public ReportsRecord value1(Integer value) {
        setReportid(value);
        return this;
    }

    @Override
    public ReportsRecord value2(Integer value) {
        setUseridreporter(value);
        return this;
    }

    @Override
    public ReportsRecord value3(Integer value) {
        setUseridreported(value);
        return this;
    }

    @Override
    public ReportsRecord value4(Integer value) {
        setReviewid(value);
        return this;
    }

    @Override
    public ReportsRecord value5(String value) {
        setReason(value);
        return this;
    }

    @Override
    public ReportsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportsRecord
     */
    public ReportsRecord() {
        super(Reports.REPORTS);
    }

    /**
     * Create a detached, initialised ReportsRecord
     */
    public ReportsRecord(Integer reportid, Integer useridreporter, Integer useridreported, Integer reviewid, String reason) {
        super(Reports.REPORTS);

        setReportid(reportid);
        setUseridreporter(useridreporter);
        setUseridreported(useridreported);
        setReviewid(reviewid);
        setReason(reason);
    }
}
