/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.harmony.tables.Series;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeriesRecord extends UpdatableRecordImpl<SeriesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.series.seriesid</code>.
     */
    public SeriesRecord setSeriesid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.series.seriesid</code>.
     */
    public Integer getSeriesid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.series.mediaid</code>.
     */
    public SeriesRecord setMediaid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.series.mediaid</code>.
     */
    public Integer getMediaid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Series.SERIES.SERIESID;
    }

    @Override
    public Field<Integer> field2() {
        return Series.SERIES.MEDIAID;
    }

    @Override
    public Integer component1() {
        return getSeriesid();
    }

    @Override
    public Integer component2() {
        return getMediaid();
    }

    @Override
    public Integer value1() {
        return getSeriesid();
    }

    @Override
    public Integer value2() {
        return getMediaid();
    }

    @Override
    public SeriesRecord value1(Integer value) {
        setSeriesid(value);
        return this;
    }

    @Override
    public SeriesRecord value2(Integer value) {
        setMediaid(value);
        return this;
    }

    @Override
    public SeriesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeriesRecord
     */
    public SeriesRecord() {
        super(Series.SERIES);
    }

    /**
     * Create a detached, initialised SeriesRecord
     */
    public SeriesRecord(Integer seriesid, Integer mediaid) {
        super(Series.SERIES);

        setSeriesid(seriesid);
        setMediaid(mediaid);
    }
}
