/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.harmony.tables.Trackers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackersRecord extends UpdatableRecordImpl<TrackersRecord> implements Record5<Integer, Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.trackers.trackerid</code>.
     */
    public TrackersRecord setTrackerid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.trackerid</code>.
     */
    public Integer getTrackerid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.trackers.mediaid</code>.
     */
    public TrackersRecord setMediaid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.mediaid</code>.
     */
    public Integer getMediaid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.trackers.userid</code>.
     */
    public TrackersRecord setUserid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>harmony.trackers.state</code>.
     */
    public TrackersRecord setState(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.state</code>.
     */
    public Integer getState() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>harmony.trackers.datetime</code>.
     */
    public TrackersRecord setDatetime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Trackers.TRACKERS.TRACKERID;
    }

    @Override
    public Field<Integer> field2() {
        return Trackers.TRACKERS.MEDIAID;
    }

    @Override
    public Field<Integer> field3() {
        return Trackers.TRACKERS.USERID;
    }

    @Override
    public Field<Integer> field4() {
        return Trackers.TRACKERS.STATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Trackers.TRACKERS.DATETIME;
    }

    @Override
    public Integer component1() {
        return getTrackerid();
    }

    @Override
    public Integer component2() {
        return getMediaid();
    }

    @Override
    public Integer component3() {
        return getUserid();
    }

    @Override
    public Integer component4() {
        return getState();
    }

    @Override
    public LocalDateTime component5() {
        return getDatetime();
    }

    @Override
    public Integer value1() {
        return getTrackerid();
    }

    @Override
    public Integer value2() {
        return getMediaid();
    }

    @Override
    public Integer value3() {
        return getUserid();
    }

    @Override
    public Integer value4() {
        return getState();
    }

    @Override
    public LocalDateTime value5() {
        return getDatetime();
    }

    @Override
    public TrackersRecord value1(Integer value) {
        setTrackerid(value);
        return this;
    }

    @Override
    public TrackersRecord value2(Integer value) {
        setMediaid(value);
        return this;
    }

    @Override
    public TrackersRecord value3(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public TrackersRecord value4(Integer value) {
        setState(value);
        return this;
    }

    @Override
    public TrackersRecord value5(LocalDateTime value) {
        setDatetime(value);
        return this;
    }

    @Override
    public TrackersRecord values(Integer value1, Integer value2, Integer value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackersRecord
     */
    public TrackersRecord() {
        super(Trackers.TRACKERS);
    }

    /**
     * Create a detached, initialised TrackersRecord
     */
    public TrackersRecord(Integer trackerid, Integer mediaid, Integer userid, Integer state, LocalDateTime datetime) {
        super(Trackers.TRACKERS);

        setTrackerid(trackerid);
        setMediaid(mediaid);
        setUserid(userid);
        setState(state);
        setDatetime(datetime);
    }
}
