/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.harmony.tables.Videogames;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VideogamesRecord extends UpdatableRecordImpl<VideogamesRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.videogames.videogameid</code>.
     */
    public VideogamesRecord setVideogameid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.videogames.videogameid</code>.
     */
    public Integer getVideogameid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.videogames.mediaid</code>.
     */
    public VideogamesRecord setMediaid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.videogames.mediaid</code>.
     */
    public Integer getMediaid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.videogames.company</code>.
     */
    public VideogamesRecord setCompany(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.videogames.company</code>.
     */
    public String getCompany() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Videogames.VIDEOGAMES.VIDEOGAMEID;
    }

    @Override
    public Field<Integer> field2() {
        return Videogames.VIDEOGAMES.MEDIAID;
    }

    @Override
    public Field<String> field3() {
        return Videogames.VIDEOGAMES.COMPANY;
    }

    @Override
    public Integer component1() {
        return getVideogameid();
    }

    @Override
    public Integer component2() {
        return getMediaid();
    }

    @Override
    public String component3() {
        return getCompany();
    }

    @Override
    public Integer value1() {
        return getVideogameid();
    }

    @Override
    public Integer value2() {
        return getMediaid();
    }

    @Override
    public String value3() {
        return getCompany();
    }

    @Override
    public VideogamesRecord value1(Integer value) {
        setVideogameid(value);
        return this;
    }

    @Override
    public VideogamesRecord value2(Integer value) {
        setMediaid(value);
        return this;
    }

    @Override
    public VideogamesRecord value3(String value) {
        setCompany(value);
        return this;
    }

    @Override
    public VideogamesRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VideogamesRecord
     */
    public VideogamesRecord() {
        super(Videogames.VIDEOGAMES);
    }

    /**
     * Create a detached, initialised VideogamesRecord
     */
    public VideogamesRecord(Integer videogameid, Integer mediaid, String company) {
        super(Videogames.VIDEOGAMES);

        setVideogameid(videogameid);
        setMediaid(mediaid);
        setCompany(company);
    }
}
