/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import src.main.java.model.Harmony;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newepisode extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newEpisode.title</code>.
     */
    public static final Parameter<String> TITLE = Internal.createParameter("title", SQLDataType.VARCHAR(500), false, false);

    /**
     * The parameter <code>harmony.newEpisode.releaseDate</code>.
     */
    public static final Parameter<LocalDate> RELEASEDATE = Internal.createParameter("releaseDate", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>harmony.newEpisode.seasonNo</code>.
     */
    public static final Parameter<Integer> SEASONNO = Internal.createParameter("seasonNo", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newEpisode.episodeName</code>.
     */
    public static final Parameter<String> EPISODENAME = Internal.createParameter("episodeName", SQLDataType.VARCHAR(60), false, false);

    /**
     * The parameter <code>harmony.newEpisode.episodeNo</code>.
     */
    public static final Parameter<Integer> EPISODENO = Internal.createParameter("episodeNo", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Newepisode() {
        super("newEpisode", Harmony.HARMONY);

        addInParameter(TITLE);
        addInParameter(RELEASEDATE);
        addInParameter(SEASONNO);
        addInParameter(EPISODENAME);
        addInParameter(EPISODENO);
    }

    /**
     * Set the <code>title</code> parameter IN value to the routine
     */
    public void setTitle(String value) {
        setValue(TITLE, value);
    }

    /**
     * Set the <code>releaseDate</code> parameter IN value to the routine
     */
    public void setReleasedate(LocalDate value) {
        setValue(RELEASEDATE, value);
    }

    /**
     * Set the <code>seasonNo</code> parameter IN value to the routine
     */
    public void setSeasonno(Integer value) {
        setValue(SEASONNO, value);
    }

    /**
     * Set the <code>episodeName</code> parameter IN value to the routine
     */
    public void setEpisodename(String value) {
        setValue(EPISODENAME, value);
    }

    /**
     * Set the <code>episodeNo</code> parameter IN value to the routine
     */
    public void setEpisodeno(Integer value) {
        setValue(EPISODENO, value);
    }
}
