/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.model.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newmediagenrebyid extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newMediaGenreById.mediaid</code>.
     */
    public static final Parameter<Integer> MEDIAID = Internal.createParameter("mediaid", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newMediaGenreById.genreid</code>.
     */
    public static final Parameter<Integer> GENREID = Internal.createParameter("genreid", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Newmediagenrebyid() {
        super("newMediaGenreById", Harmony.HARMONY);

        addInParameter(MEDIAID);
        addInParameter(GENREID);
    }

    /**
     * Set the <code>mediaid</code> parameter IN value to the routine
     */
    public void setMediaid(Integer value) {
        setValue(MEDIAID, value);
    }

    /**
     * Set the <code>genreid</code> parameter IN value to the routine
     */
    public void setGenreid(Integer value) {
        setValue(GENREID, value);
    }
}
