/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import src.main.java.model.Harmony;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newpersonbook extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newPersonBook.personname</code>.
     */
    public static final Parameter<String> PERSONNAME = Internal.createParameter("personname", SQLDataType.VARCHAR(60), false, false);

    /**
     * The parameter <code>harmony.newPersonBook.date</code>.
     */
    public static final Parameter<LocalDate> DATE = Internal.createParameter("date", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>harmony.newPersonBook.title</code>.
     */
    public static final Parameter<String> TITLE = Internal.createParameter("title", SQLDataType.VARCHAR(500), false, false);

    /**
     * The parameter <code>harmony.newPersonBook.releaseDate</code>.
     */
    public static final Parameter<LocalDate> RELEASEDATE = Internal.createParameter("releaseDate", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>harmony.newPersonBook.role</code>.
     */
    public static final Parameter<String> ROLE = Internal.createParameter("role", SQLDataType.VARCHAR(120), false, false);

    /**
     * Create a new routine call instance
     */
    public Newpersonbook() {
        super("newPersonBook", Harmony.HARMONY);

        addInParameter(PERSONNAME);
        addInParameter(DATE);
        addInParameter(TITLE);
        addInParameter(RELEASEDATE);
        addInParameter(ROLE);
    }

    /**
     * Set the <code>personname</code> parameter IN value to the routine
     */
    public void setPersonname(String value) {
        setValue(PERSONNAME, value);
    }

    /**
     * Set the <code>date</code> parameter IN value to the routine
     */
    public void setDate(LocalDate value) {
        setValue(DATE, value);
    }

    /**
     * Set the <code>title</code> parameter IN value to the routine
     */
    public void setTitle(String value) {
        setValue(TITLE, value);
    }

    /**
     * Set the <code>releaseDate</code> parameter IN value to the routine
     */
    public void setReleasedate(LocalDate value) {
        setValue(RELEASEDATE, value);
    }

    /**
     * Set the <code>role</code> parameter IN value to the routine
     */
    public void setRole(String value) {
        setValue(ROLE, value);
    }
}
