/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import java.time.LocalDate;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.model.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newperson extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newPerson.name</code>.
     */
    public static final Parameter<String> NAME = Internal.createParameter("name", SQLDataType.VARCHAR(60), false, false);

    /**
     * The parameter <code>harmony.newPerson.birthdate</code>.
     */
    public static final Parameter<LocalDate> BIRTHDATE = Internal.createParameter("birthdate", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>harmony.newPerson.picture</code>.
     */
    public static final Parameter<String> PICTURE = Internal.createParameter("picture", SQLDataType.VARCHAR(240), false, false);

    /**
     * Create a new routine call instance
     */
    public Newperson() {
        super("newPerson", Harmony.HARMONY);

        addInParameter(NAME);
        addInParameter(BIRTHDATE);
        addInParameter(PICTURE);
    }

    /**
     * Set the <code>name</code> parameter IN value to the routine
     */
    public void setName_(String value) {
        setValue(NAME, value);
    }

    /**
     * Set the <code>birthdate</code> parameter IN value to the routine
     */
    public void setBirthdate(LocalDate value) {
        setValue(BIRTHDATE, value);
    }

    /**
     * Set the <code>picture</code> parameter IN value to the routine
     */
    public void setPicture(String value) {
        setValue(PICTURE, value);
    }
}
