/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.model.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newpersonepisodebyid extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newPersonEpisodeById.personid</code>.
     */
    public static final Parameter<Integer> PERSONID = Internal.createParameter("personid", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newPersonEpisodeById.episodeid</code>.
     */
    public static final Parameter<Integer> EPISODEID = Internal.createParameter("episodeid", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newPersonEpisodeById.role</code>.
     */
    public static final Parameter<String> ROLE = Internal.createParameter("role", SQLDataType.VARCHAR(120), false, false);

    /**
     * The parameter <code>harmony.newPersonEpisodeById.roletype</code>.
     */
    public static final Parameter<Byte> ROLETYPE = Internal.createParameter("roletype", SQLDataType.TINYINT, false, false);

    /**
     * Create a new routine call instance
     */
    public Newpersonepisodebyid() {
        super("newPersonEpisodeById", Harmony.HARMONY);

        addInParameter(PERSONID);
        addInParameter(EPISODEID);
        addInParameter(ROLE);
        addInParameter(ROLETYPE);
    }

    /**
     * Set the <code>personid</code> parameter IN value to the routine
     */
    public void setPersonid(Integer value) {
        setValue(PERSONID, value);
    }

    /**
     * Set the <code>episodeid</code> parameter IN value to the routine
     */
    public void setEpisodeid(Integer value) {
        setValue(EPISODEID, value);
    }

    /**
     * Set the <code>role</code> parameter IN value to the routine
     */
    public void setRole(String value) {
        setValue(ROLE, value);
    }

    /**
     * Set the <code>roletype</code> parameter IN value to the routine
     */
    public void setRoletype(Byte value) {
        setValue(ROLETYPE, value);
    }
}
