/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import java.time.LocalDate;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.model.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newpersonepisode extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newPersonEpisode.personname</code>.
     */
    public static final Parameter<String> PERSONNAME = Internal.createParameter("personname", SQLDataType.VARCHAR(60), false, false);

    /**
     * The parameter <code>harmony.newPersonEpisode.date</code>.
     */
    public static final Parameter<LocalDate> DATE = Internal.createParameter("date", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>harmony.newPersonEpisode.title</code>.
     */
    public static final Parameter<String> TITLE = Internal.createParameter("title", SQLDataType.VARCHAR(120), false, false);

    /**
     * The parameter <code>harmony.newPersonEpisode.releaseDate</code>.
     */
    public static final Parameter<LocalDate> RELEASEDATE = Internal.createParameter("releaseDate", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>harmony.newPersonEpisode.seasonNo</code>.
     */
    public static final Parameter<Integer> SEASONNO = Internal.createParameter("seasonNo", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newPersonEpisode.episodeNo</code>.
     */
    public static final Parameter<Integer> EPISODENO = Internal.createParameter("episodeNo", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newPersonEpisode.role</code>.
     */
    public static final Parameter<String> ROLE = Internal.createParameter("role", SQLDataType.VARCHAR(120), false, false);

    /**
     * The parameter <code>harmony.newPersonEpisode.roletype</code>.
     */
    public static final Parameter<Byte> ROLETYPE = Internal.createParameter("roletype", SQLDataType.TINYINT, false, false);

    /**
     * Create a new routine call instance
     */
    public Newpersonepisode() {
        super("newPersonEpisode", Harmony.HARMONY);

        addInParameter(PERSONNAME);
        addInParameter(DATE);
        addInParameter(TITLE);
        addInParameter(RELEASEDATE);
        addInParameter(SEASONNO);
        addInParameter(EPISODENO);
        addInParameter(ROLE);
        addInParameter(ROLETYPE);
    }

    /**
     * Set the <code>personname</code> parameter IN value to the routine
     */
    public void setPersonname(String value) {
        setValue(PERSONNAME, value);
    }

    /**
     * Set the <code>date</code> parameter IN value to the routine
     */
    public void setDate(LocalDate value) {
        setValue(DATE, value);
    }

    /**
     * Set the <code>title</code> parameter IN value to the routine
     */
    public void setTitle(String value) {
        setValue(TITLE, value);
    }

    /**
     * Set the <code>releaseDate</code> parameter IN value to the routine
     */
    public void setReleasedate(LocalDate value) {
        setValue(RELEASEDATE, value);
    }

    /**
     * Set the <code>seasonNo</code> parameter IN value to the routine
     */
    public void setSeasonno(Integer value) {
        setValue(SEASONNO, value);
    }

    /**
     * Set the <code>episodeNo</code> parameter IN value to the routine
     */
    public void setEpisodeno(Integer value) {
        setValue(EPISODENO, value);
    }

    /**
     * Set the <code>role</code> parameter IN value to the routine
     */
    public void setRole(String value) {
        setValue(ROLE, value);
    }

    /**
     * Set the <code>roletype</code> parameter IN value to the routine
     */
    public void setRoletype(Byte value) {
        setValue(ROLETYPE, value);
    }
}
