/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import src.main.java.model.Harmony;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newseason extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newSeason.title</code>.
     */
    public static final Parameter<String> TITLE = Internal.createParameter("title", SQLDataType.VARCHAR(500), false, false);

    /**
     * The parameter <code>harmony.newSeason.releaseDate</code>.
     */
    public static final Parameter<LocalDate> RELEASEDATE = Internal.createParameter("releaseDate", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>harmony.newSeason.seasonNo</code>.
     */
    public static final Parameter<Integer> SEASONNO = Internal.createParameter("seasonNo", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newSeason.noEpisodes</code>.
     */
    public static final Parameter<Integer> NOEPISODES = Internal.createParameter("noEpisodes", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Newseason() {
        super("newSeason", Harmony.HARMONY);

        addInParameter(TITLE);
        addInParameter(RELEASEDATE);
        addInParameter(SEASONNO);
        addInParameter(NOEPISODES);
    }

    /**
     * Set the <code>title</code> parameter IN value to the routine
     */
    public void setTitle(String value) {
        setValue(TITLE, value);
    }

    /**
     * Set the <code>releaseDate</code> parameter IN value to the routine
     */
    public void setReleasedate(LocalDate value) {
        setValue(RELEASEDATE, value);
    }

    /**
     * Set the <code>seasonNo</code> parameter IN value to the routine
     */
    public void setSeasonno(Integer value) {
        setValue(SEASONNO, value);
    }

    /**
     * Set the <code>noEpisodes</code> parameter IN value to the routine
     */
    public void setNoepisodes(Integer value) {
        setValue(NOEPISODES, value);
    }
}
