/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.model.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newseasonbyid extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newSeasonById.seriesid</code>.
     */
    public static final Parameter<Integer> SERIESID = Internal.createParameter("seriesid", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newSeasonById.seasonNo</code>.
     */
    public static final Parameter<Integer> SEASONNO = Internal.createParameter("seasonNo", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newSeasonById.noEpisodes</code>.
     */
    public static final Parameter<Integer> NOEPISODES = Internal.createParameter("noEpisodes", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Newseasonbyid() {
        super("newSeasonById", Harmony.HARMONY);

        addInParameter(SERIESID);
        addInParameter(SEASONNO);
        addInParameter(NOEPISODES);
    }

    /**
     * Set the <code>seriesid</code> parameter IN value to the routine
     */
    public void setSeriesid(Integer value) {
        setValue(SERIESID, value);
    }

    /**
     * Set the <code>seasonNo</code> parameter IN value to the routine
     */
    public void setSeasonno(Integer value) {
        setValue(SEASONNO, value);
    }

    /**
     * Set the <code>noEpisodes</code> parameter IN value to the routine
     */
    public void setNoepisodes(Integer value) {
        setValue(NOEPISODES, value);
    }
}
