/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.model.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newuser extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newUser.username</code>.
     */
    public static final Parameter<String> USERNAME = Internal.createParameter("username", SQLDataType.VARCHAR(15), false, false);

    /**
     * The parameter <code>harmony.newUser.email</code>.
     */
    public static final Parameter<String> EMAIL = Internal.createParameter("email", SQLDataType.VARCHAR(100), false, false);

    /**
     * The parameter <code>harmony.newUser.password</code>.
     */
    public static final Parameter<String> PASSWORD = Internal.createParameter("password", SQLDataType.VARCHAR(36), false, false);

    /**
     * The parameter <code>harmony.newUser.isAdmin</code>.
     */
    public static final Parameter<Byte> ISADMIN = Internal.createParameter("isAdmin", SQLDataType.TINYINT, false, false);

    /**
     * Create a new routine call instance
     */
    public Newuser() {
        super("newUser", Harmony.HARMONY);

        addInParameter(USERNAME);
        addInParameter(EMAIL);
        addInParameter(PASSWORD);
        addInParameter(ISADMIN);
    }

    /**
     * Set the <code>username</code> parameter IN value to the routine
     */
    public void setUsername(String value) {
        setValue(USERNAME, value);
    }

    /**
     * Set the <code>email</code> parameter IN value to the routine
     */
    public void setEmail(String value) {
        setValue(EMAIL, value);
    }

    /**
     * Set the <code>password</code> parameter IN value to the routine
     */
    public void setPassword(String value) {
        setValue(PASSWORD, value);
    }

    /**
     * Set the <code>isAdmin</code> parameter IN value to the routine
     */
    public void setIsadmin(Byte value) {
        setValue(ISADMIN, value);
    }
}
