/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.model.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newvideogameplatformbyid extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newVideogamePlatformById.mediaid</code>.
     */
    public static final Parameter<Integer> MEDIAID = Internal.createParameter("mediaid", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newVideogamePlatformById.platformid</code>.
     */
    public static final Parameter<Integer> PLATFORMID = Internal.createParameter("platformid", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Newvideogameplatformbyid() {
        super("newVideogamePlatformById", Harmony.HARMONY);

        addInParameter(MEDIAID);
        addInParameter(PLATFORMID);
    }

    /**
     * Set the <code>mediaid</code> parameter IN value to the routine
     */
    public void setMediaid(Integer value) {
        setValue(MEDIAID, value);
    }

    /**
     * Set the <code>platformid</code> parameter IN value to the routine
     */
    public void setPlatformid(Integer value) {
        setValue(PLATFORMID, value);
    }
}
