/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import src.main.java.model.Harmony;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newvideogameplatform extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newVideogamePlatform.platformName</code>.
     */
    public static final Parameter<String> PLATFORMNAME = Internal.createParameter("platformName", SQLDataType.VARCHAR(60), false, false);

    /**
     * The parameter <code>harmony.newVideogamePlatform.title</code>.
     */
    public static final Parameter<String> TITLE = Internal.createParameter("title", SQLDataType.VARCHAR(500), false, false);

    /**
     * The parameter <code>harmony.newVideogamePlatform.releaseDate</code>.
     */
    public static final Parameter<LocalDate> RELEASEDATE = Internal.createParameter("releaseDate", SQLDataType.LOCALDATE, false, false);

    /**
     * Create a new routine call instance
     */
    public Newvideogameplatform() {
        super("newVideogamePlatform", Harmony.HARMONY);

        addInParameter(PLATFORMNAME);
        addInParameter(TITLE);
        addInParameter(RELEASEDATE);
    }

    /**
     * Set the <code>platformName</code> parameter IN value to the routine
     */
    public void setPlatformname(String value) {
        setValue(PLATFORMNAME, value);
    }

    /**
     * Set the <code>title</code> parameter IN value to the routine
     */
    public void setTitle(String value) {
        setValue(TITLE, value);
    }

    /**
     * Set the <code>releaseDate</code> parameter IN value to the routine
     */
    public void setReleasedate(LocalDate value) {
        setValue(RELEASEDATE, value);
    }
}
