/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Admins implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer adminid;
    private Integer userid;

    public Admins() {}

    public Admins(Admins value) {
        this.adminid = value.adminid;
        this.userid = value.userid;
    }

    public Admins(
        Integer adminid,
        Integer userid
    ) {
        this.adminid = adminid;
        this.userid = userid;
    }

    /**
     * Getter for <code>harmony.admins.adminid</code>.
     */
    public Integer getAdminid() {
        return this.adminid;
    }

    /**
     * Setter for <code>harmony.admins.adminid</code>.
     */
    public Admins setAdminid(Integer adminid) {
        this.adminid = adminid;
        return this;
    }

    /**
     * Getter for <code>harmony.admins.userid</code>.
     */
    public Integer getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>harmony.admins.userid</code>.
     */
    public Admins setUserid(Integer userid) {
        this.userid = userid;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Admins other = (Admins) obj;
        if (adminid == null) {
            if (other.adminid != null)
                return false;
        }
        else if (!adminid.equals(other.adminid))
            return false;
        if (userid == null) {
            if (other.userid != null)
                return false;
        }
        else if (!userid.equals(other.userid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.adminid == null) ? 0 : this.adminid.hashCode());
        result = prime * result + ((this.userid == null) ? 0 : this.userid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Admins (");

        sb.append(adminid);
        sb.append(", ").append(userid);

        sb.append(")");
        return sb.toString();
    }
}
