/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Books implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer bookid;
    private Integer mediaid;
    private String  collection;
    private Integer number;

    public Books() {}

    public Books(Books value) {
        this.bookid = value.bookid;
        this.mediaid = value.mediaid;
        this.collection = value.collection;
        this.number = value.number;
    }

    public Books(
        Integer bookid,
        Integer mediaid,
        String  collection,
        Integer number
    ) {
        this.bookid = bookid;
        this.mediaid = mediaid;
        this.collection = collection;
        this.number = number;
    }

    /**
     * Getter for <code>harmony.books.bookid</code>.
     */
    public Integer getBookid() {
        return this.bookid;
    }

    /**
     * Setter for <code>harmony.books.bookid</code>.
     */
    public Books setBookid(Integer bookid) {
        this.bookid = bookid;
        return this;
    }

    /**
     * Getter for <code>harmony.books.mediaid</code>.
     */
    public Integer getMediaid() {
        return this.mediaid;
    }

    /**
     * Setter for <code>harmony.books.mediaid</code>.
     */
    public Books setMediaid(Integer mediaid) {
        this.mediaid = mediaid;
        return this;
    }

    /**
     * Getter for <code>harmony.books.collection</code>.
     */
    public String getCollection() {
        return this.collection;
    }

    /**
     * Setter for <code>harmony.books.collection</code>.
     */
    public Books setCollection(String collection) {
        this.collection = collection;
        return this;
    }

    /**
     * Getter for <code>harmony.books.number</code>.
     */
    public Integer getNumber() {
        return this.number;
    }

    /**
     * Setter for <code>harmony.books.number</code>.
     */
    public Books setNumber(Integer number) {
        this.number = number;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Books other = (Books) obj;
        if (bookid == null) {
            if (other.bookid != null)
                return false;
        }
        else if (!bookid.equals(other.bookid))
            return false;
        if (mediaid == null) {
            if (other.mediaid != null)
                return false;
        }
        else if (!mediaid.equals(other.mediaid))
            return false;
        if (collection == null) {
            if (other.collection != null)
                return false;
        }
        else if (!collection.equals(other.collection))
            return false;
        if (number == null) {
            if (other.number != null)
                return false;
        }
        else if (!number.equals(other.number))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.bookid == null) ? 0 : this.bookid.hashCode());
        result = prime * result + ((this.mediaid == null) ? 0 : this.mediaid.hashCode());
        result = prime * result + ((this.collection == null) ? 0 : this.collection.hashCode());
        result = prime * result + ((this.number == null) ? 0 : this.number.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Books (");

        sb.append(bookid);
        sb.append(", ").append(mediaid);
        sb.append(", ").append(collection);
        sb.append(", ").append(number);

        sb.append(")");
        return sb.toString();
    }
}
