/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Listmedia implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       elementid;
    private Integer       listid;
    private Integer       mediaid;
    private LocalDateTime addeddate;

    public Listmedia() {}

    public Listmedia(Listmedia value) {
        this.elementid = value.elementid;
        this.listid = value.listid;
        this.mediaid = value.mediaid;
        this.addeddate = value.addeddate;
    }

    public Listmedia(
        Integer       elementid,
        Integer       listid,
        Integer       mediaid,
        LocalDateTime addeddate
    ) {
        this.elementid = elementid;
        this.listid = listid;
        this.mediaid = mediaid;
        this.addeddate = addeddate;
    }

    /**
     * Getter for <code>harmony.listmedia.elementid</code>.
     */
    public Integer getElementid() {
        return this.elementid;
    }

    /**
     * Setter for <code>harmony.listmedia.elementid</code>.
     */
    public Listmedia setElementid(Integer elementid) {
        this.elementid = elementid;
        return this;
    }

    /**
     * Getter for <code>harmony.listmedia.listid</code>.
     */
    public Integer getListid() {
        return this.listid;
    }

    /**
     * Setter for <code>harmony.listmedia.listid</code>.
     */
    public Listmedia setListid(Integer listid) {
        this.listid = listid;
        return this;
    }

    /**
     * Getter for <code>harmony.listmedia.mediaid</code>.
     */
    public Integer getMediaid() {
        return this.mediaid;
    }

    /**
     * Setter for <code>harmony.listmedia.mediaid</code>.
     */
    public Listmedia setMediaid(Integer mediaid) {
        this.mediaid = mediaid;
        return this;
    }

    /**
     * Getter for <code>harmony.listmedia.addedDate</code>.
     */
    public LocalDateTime getAddeddate() {
        return this.addeddate;
    }

    /**
     * Setter for <code>harmony.listmedia.addedDate</code>.
     */
    public Listmedia setAddeddate(LocalDateTime addeddate) {
        this.addeddate = addeddate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Listmedia other = (Listmedia) obj;
        if (elementid == null) {
            if (other.elementid != null)
                return false;
        }
        else if (!elementid.equals(other.elementid))
            return false;
        if (listid == null) {
            if (other.listid != null)
                return false;
        }
        else if (!listid.equals(other.listid))
            return false;
        if (mediaid == null) {
            if (other.mediaid != null)
                return false;
        }
        else if (!mediaid.equals(other.mediaid))
            return false;
        if (addeddate == null) {
            if (other.addeddate != null)
                return false;
        }
        else if (!addeddate.equals(other.addeddate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.elementid == null) ? 0 : this.elementid.hashCode());
        result = prime * result + ((this.listid == null) ? 0 : this.listid.hashCode());
        result = prime * result + ((this.mediaid == null) ? 0 : this.mediaid.hashCode());
        result = prime * result + ((this.addeddate == null) ? 0 : this.addeddate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Listmedia (");

        sb.append(elementid);
        sb.append(", ").append(listid);
        sb.append(", ").append(mediaid);
        sb.append(", ").append(addeddate);

        sb.append(")");
        return sb.toString();
    }
}
