/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Media implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   mediaid;
    private String    title;
    private LocalDate releasedate;
    private String    coverimage;
    private String    backgroundimage;
    private String    synopsis;
    private Double    avgrating;
    private Integer   externalid;

    public Media() {}

    public Media(Media value) {
        this.mediaid = value.mediaid;
        this.title = value.title;
        this.releasedate = value.releasedate;
        this.coverimage = value.coverimage;
        this.backgroundimage = value.backgroundimage;
        this.synopsis = value.synopsis;
        this.avgrating = value.avgrating;
        this.externalid = value.externalid;
    }

    public Media(
        Integer   mediaid,
        String    title,
        LocalDate releasedate,
        String    coverimage,
        String    backgroundimage,
        String    synopsis,
        Double    avgrating,
        Integer   externalid
    ) {
        this.mediaid = mediaid;
        this.title = title;
        this.releasedate = releasedate;
        this.coverimage = coverimage;
        this.backgroundimage = backgroundimage;
        this.synopsis = synopsis;
        this.avgrating = avgrating;
        this.externalid = externalid;
    }

    /**
     * Getter for <code>harmony.media.mediaid</code>.
     */
    public Integer getMediaid() {
        return this.mediaid;
    }

    /**
     * Setter for <code>harmony.media.mediaid</code>.
     */
    public Media setMediaid(Integer mediaid) {
        this.mediaid = mediaid;
        return this;
    }

    /**
     * Getter for <code>harmony.media.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>harmony.media.title</code>.
     */
    public Media setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>harmony.media.releaseDate</code>.
     */
    public LocalDate getReleasedate() {
        return this.releasedate;
    }

    /**
     * Setter for <code>harmony.media.releaseDate</code>.
     */
    public Media setReleasedate(LocalDate releasedate) {
        this.releasedate = releasedate;
        return this;
    }

    /**
     * Getter for <code>harmony.media.coverImage</code>.
     */
    public String getCoverimage() {
        return this.coverimage;
    }

    /**
     * Setter for <code>harmony.media.coverImage</code>.
     */
    public Media setCoverimage(String coverimage) {
        this.coverimage = coverimage;
        return this;
    }

    /**
     * Getter for <code>harmony.media.backgroundImage</code>.
     */
    public String getBackgroundimage() {
        return this.backgroundimage;
    }

    /**
     * Setter for <code>harmony.media.backgroundImage</code>.
     */
    public Media setBackgroundimage(String backgroundimage) {
        this.backgroundimage = backgroundimage;
        return this;
    }

    /**
     * Getter for <code>harmony.media.synopsis</code>.
     */
    public String getSynopsis() {
        return this.synopsis;
    }

    /**
     * Setter for <code>harmony.media.synopsis</code>.
     */
    public Media setSynopsis(String synopsis) {
        this.synopsis = synopsis;
        return this;
    }

    /**
     * Getter for <code>harmony.media.avgRating</code>.
     */
    public Double getAvgrating() {
        return this.avgrating;
    }

    /**
     * Setter for <code>harmony.media.avgRating</code>.
     */
    public Media setAvgrating(Double avgrating) {
        this.avgrating = avgrating;
        return this;
    }

    /**
     * Getter for <code>harmony.media.externalId</code>.
     */
    public Integer getExternalid() {
        return this.externalid;
    }

    /**
     * Setter for <code>harmony.media.externalId</code>.
     */
    public Media setExternalid(Integer externalid) {
        this.externalid = externalid;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Media other = (Media) obj;
        if (mediaid == null) {
            if (other.mediaid != null)
                return false;
        }
        else if (!mediaid.equals(other.mediaid))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (releasedate == null) {
            if (other.releasedate != null)
                return false;
        }
        else if (!releasedate.equals(other.releasedate))
            return false;
        if (coverimage == null) {
            if (other.coverimage != null)
                return false;
        }
        else if (!coverimage.equals(other.coverimage))
            return false;
        if (backgroundimage == null) {
            if (other.backgroundimage != null)
                return false;
        }
        else if (!backgroundimage.equals(other.backgroundimage))
            return false;
        if (synopsis == null) {
            if (other.synopsis != null)
                return false;
        }
        else if (!synopsis.equals(other.synopsis))
            return false;
        if (avgrating == null) {
            if (other.avgrating != null)
                return false;
        }
        else if (!avgrating.equals(other.avgrating))
            return false;
        if (externalid == null) {
            if (other.externalid != null)
                return false;
        }
        else if (!externalid.equals(other.externalid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mediaid == null) ? 0 : this.mediaid.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.releasedate == null) ? 0 : this.releasedate.hashCode());
        result = prime * result + ((this.coverimage == null) ? 0 : this.coverimage.hashCode());
        result = prime * result + ((this.backgroundimage == null) ? 0 : this.backgroundimage.hashCode());
        result = prime * result + ((this.synopsis == null) ? 0 : this.synopsis.hashCode());
        result = prime * result + ((this.avgrating == null) ? 0 : this.avgrating.hashCode());
        result = prime * result + ((this.externalid == null) ? 0 : this.externalid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Media (");

        sb.append(mediaid);
        sb.append(", ").append(title);
        sb.append(", ").append(releasedate);
        sb.append(", ").append(coverimage);
        sb.append(", ").append(backgroundimage);
        sb.append(", ").append(synopsis);
        sb.append(", ").append(avgrating);
        sb.append(", ").append(externalid);

        sb.append(")");
        return sb.toString();
    }
}
