/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reports implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer reportid;
    private Integer useridreporter;
    private Integer useridreported;
    private Integer reviewid;
    private String  reason;

    public Reports() {}

    public Reports(Reports value) {
        this.reportid = value.reportid;
        this.useridreporter = value.useridreporter;
        this.useridreported = value.useridreported;
        this.reviewid = value.reviewid;
        this.reason = value.reason;
    }

    public Reports(
        Integer reportid,
        Integer useridreporter,
        Integer useridreported,
        Integer reviewid,
        String  reason
    ) {
        this.reportid = reportid;
        this.useridreporter = useridreporter;
        this.useridreported = useridreported;
        this.reviewid = reviewid;
        this.reason = reason;
    }

    /**
     * Getter for <code>harmony.reports.reportid</code>.
     */
    public Integer getReportid() {
        return this.reportid;
    }

    /**
     * Setter for <code>harmony.reports.reportid</code>.
     */
    public Reports setReportid(Integer reportid) {
        this.reportid = reportid;
        return this;
    }

    /**
     * Getter for <code>harmony.reports.useridreporter</code>.
     */
    public Integer getUseridreporter() {
        return this.useridreporter;
    }

    /**
     * Setter for <code>harmony.reports.useridreporter</code>.
     */
    public Reports setUseridreporter(Integer useridreporter) {
        this.useridreporter = useridreporter;
        return this;
    }

    /**
     * Getter for <code>harmony.reports.useridreported</code>.
     */
    public Integer getUseridreported() {
        return this.useridreported;
    }

    /**
     * Setter for <code>harmony.reports.useridreported</code>.
     */
    public Reports setUseridreported(Integer useridreported) {
        this.useridreported = useridreported;
        return this;
    }

    /**
     * Getter for <code>harmony.reports.reviewid</code>.
     */
    public Integer getReviewid() {
        return this.reviewid;
    }

    /**
     * Setter for <code>harmony.reports.reviewid</code>.
     */
    public Reports setReviewid(Integer reviewid) {
        this.reviewid = reviewid;
        return this;
    }

    /**
     * Getter for <code>harmony.reports.reason</code>.
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * Setter for <code>harmony.reports.reason</code>.
     */
    public Reports setReason(String reason) {
        this.reason = reason;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Reports other = (Reports) obj;
        if (reportid == null) {
            if (other.reportid != null)
                return false;
        }
        else if (!reportid.equals(other.reportid))
            return false;
        if (useridreporter == null) {
            if (other.useridreporter != null)
                return false;
        }
        else if (!useridreporter.equals(other.useridreporter))
            return false;
        if (useridreported == null) {
            if (other.useridreported != null)
                return false;
        }
        else if (!useridreported.equals(other.useridreported))
            return false;
        if (reviewid == null) {
            if (other.reviewid != null)
                return false;
        }
        else if (!reviewid.equals(other.reviewid))
            return false;
        if (reason == null) {
            if (other.reason != null)
                return false;
        }
        else if (!reason.equals(other.reason))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reportid == null) ? 0 : this.reportid.hashCode());
        result = prime * result + ((this.useridreporter == null) ? 0 : this.useridreporter.hashCode());
        result = prime * result + ((this.useridreported == null) ? 0 : this.useridreported.hashCode());
        result = prime * result + ((this.reviewid == null) ? 0 : this.reviewid.hashCode());
        result = prime * result + ((this.reason == null) ? 0 : this.reason.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reports (");

        sb.append(reportid);
        sb.append(", ").append(useridreporter);
        sb.append(", ").append(useridreported);
        sb.append(", ").append(reviewid);
        sb.append(", ").append(reason);

        sb.append(")");
        return sb.toString();
    }
}
