/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reviews implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       reviewid;
    private Integer       userid;
    private Integer       mediaid;
    private LocalDateTime datetime;
    private Double        rating;
    private String        review;
    private Integer       likes;

    public Reviews() {}

    public Reviews(Reviews value) {
        this.reviewid = value.reviewid;
        this.userid = value.userid;
        this.mediaid = value.mediaid;
        this.datetime = value.datetime;
        this.rating = value.rating;
        this.review = value.review;
        this.likes = value.likes;
    }

    public Reviews(
        Integer       reviewid,
        Integer       userid,
        Integer       mediaid,
        LocalDateTime datetime,
        Double        rating,
        String        review,
        Integer       likes
    ) {
        this.reviewid = reviewid;
        this.userid = userid;
        this.mediaid = mediaid;
        this.datetime = datetime;
        this.rating = rating;
        this.review = review;
        this.likes = likes;
    }

    /**
     * Getter for <code>harmony.reviews.reviewid</code>.
     */
    public Integer getReviewid() {
        return this.reviewid;
    }

    /**
     * Setter for <code>harmony.reviews.reviewid</code>.
     */
    public Reviews setReviewid(Integer reviewid) {
        this.reviewid = reviewid;
        return this;
    }

    /**
     * Getter for <code>harmony.reviews.userid</code>.
     */
    public Integer getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>harmony.reviews.userid</code>.
     */
    public Reviews setUserid(Integer userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>harmony.reviews.mediaid</code>.
     */
    public Integer getMediaid() {
        return this.mediaid;
    }

    /**
     * Setter for <code>harmony.reviews.mediaid</code>.
     */
    public Reviews setMediaid(Integer mediaid) {
        this.mediaid = mediaid;
        return this;
    }

    /**
     * Getter for <code>harmony.reviews.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return this.datetime;
    }

    /**
     * Setter for <code>harmony.reviews.datetime</code>.
     */
    public Reviews setDatetime(LocalDateTime datetime) {
        this.datetime = datetime;
        return this;
    }

    /**
     * Getter for <code>harmony.reviews.rating</code>.
     */
    public Double getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>harmony.reviews.rating</code>.
     */
    public Reviews setRating(Double rating) {
        this.rating = rating;
        return this;
    }

    /**
     * Getter for <code>harmony.reviews.review</code>.
     */
    public String getReview() {
        return this.review;
    }

    /**
     * Setter for <code>harmony.reviews.review</code>.
     */
    public Reviews setReview(String review) {
        this.review = review;
        return this;
    }

    /**
     * Getter for <code>harmony.reviews.likes</code>.
     */
    public Integer getLikes() {
        return this.likes;
    }

    /**
     * Setter for <code>harmony.reviews.likes</code>.
     */
    public Reviews setLikes(Integer likes) {
        this.likes = likes;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Reviews other = (Reviews) obj;
        if (reviewid == null) {
            if (other.reviewid != null)
                return false;
        }
        else if (!reviewid.equals(other.reviewid))
            return false;
        if (userid == null) {
            if (other.userid != null)
                return false;
        }
        else if (!userid.equals(other.userid))
            return false;
        if (mediaid == null) {
            if (other.mediaid != null)
                return false;
        }
        else if (!mediaid.equals(other.mediaid))
            return false;
        if (datetime == null) {
            if (other.datetime != null)
                return false;
        }
        else if (!datetime.equals(other.datetime))
            return false;
        if (rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!rating.equals(other.rating))
            return false;
        if (review == null) {
            if (other.review != null)
                return false;
        }
        else if (!review.equals(other.review))
            return false;
        if (likes == null) {
            if (other.likes != null)
                return false;
        }
        else if (!likes.equals(other.likes))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reviewid == null) ? 0 : this.reviewid.hashCode());
        result = prime * result + ((this.userid == null) ? 0 : this.userid.hashCode());
        result = prime * result + ((this.mediaid == null) ? 0 : this.mediaid.hashCode());
        result = prime * result + ((this.datetime == null) ? 0 : this.datetime.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.review == null) ? 0 : this.review.hashCode());
        result = prime * result + ((this.likes == null) ? 0 : this.likes.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reviews (");

        sb.append(reviewid);
        sb.append(", ").append(userid);
        sb.append(", ").append(mediaid);
        sb.append(", ").append(datetime);
        sb.append(", ").append(rating);
        sb.append(", ").append(review);
        sb.append(", ").append(likes);

        sb.append(")");
        return sb.toString();
    }
}
