/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   userid;
    private String    username;
    private String    email;
    private String    password;
    private LocalDate creationdate;

    public Users() {}

    public Users(Users value) {
        this.userid = value.userid;
        this.username = value.username;
        this.email = value.email;
        this.password = value.password;
        this.creationdate = value.creationdate;
    }

    public Users(
        Integer   userid,
        String    username,
        String    email,
        String    password,
        LocalDate creationdate
    ) {
        this.userid = userid;
        this.username = username;
        this.email = email;
        this.password = password;
        this.creationdate = creationdate;
    }

    /**
     * Getter for <code>harmony.users.userid</code>.
     */
    public Integer getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>harmony.users.userid</code>.
     */
    public Users setUserid(Integer userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>harmony.users.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>harmony.users.username</code>.
     */
    public Users setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>harmony.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>harmony.users.email</code>.
     */
    public Users setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>harmony.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>harmony.users.password</code>.
     */
    public Users setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>harmony.users.creationDate</code>.
     */
    public LocalDate getCreationdate() {
        return this.creationdate;
    }

    /**
     * Setter for <code>harmony.users.creationDate</code>.
     */
    public Users setCreationdate(LocalDate creationdate) {
        this.creationdate = creationdate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (userid == null) {
            if (other.userid != null)
                return false;
        }
        else if (!userid.equals(other.userid))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        }
        else if (!username.equals(other.username))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (creationdate == null) {
            if (other.creationdate != null)
                return false;
        }
        else if (!creationdate.equals(other.creationdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userid == null) ? 0 : this.userid.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.creationdate == null) ? 0 : this.creationdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userid);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(creationdate);

        sb.append(")");
        return sb.toString();
    }
}
