/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Videogames implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer videogameid;
    private Integer mediaid;
    private String  company;

    public Videogames() {}

    public Videogames(Videogames value) {
        this.videogameid = value.videogameid;
        this.mediaid = value.mediaid;
        this.company = value.company;
    }

    public Videogames(
        Integer videogameid,
        Integer mediaid,
        String  company
    ) {
        this.videogameid = videogameid;
        this.mediaid = mediaid;
        this.company = company;
    }

    /**
     * Getter for <code>harmony.videogames.videogameid</code>.
     */
    public Integer getVideogameid() {
        return this.videogameid;
    }

    /**
     * Setter for <code>harmony.videogames.videogameid</code>.
     */
    public Videogames setVideogameid(Integer videogameid) {
        this.videogameid = videogameid;
        return this;
    }

    /**
     * Getter for <code>harmony.videogames.mediaid</code>.
     */
    public Integer getMediaid() {
        return this.mediaid;
    }

    /**
     * Setter for <code>harmony.videogames.mediaid</code>.
     */
    public Videogames setMediaid(Integer mediaid) {
        this.mediaid = mediaid;
        return this;
    }

    /**
     * Getter for <code>harmony.videogames.company</code>.
     */
    public String getCompany() {
        return this.company;
    }

    /**
     * Setter for <code>harmony.videogames.company</code>.
     */
    public Videogames setCompany(String company) {
        this.company = company;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Videogames other = (Videogames) obj;
        if (videogameid == null) {
            if (other.videogameid != null)
                return false;
        }
        else if (!videogameid.equals(other.videogameid))
            return false;
        if (mediaid == null) {
            if (other.mediaid != null)
                return false;
        }
        else if (!mediaid.equals(other.mediaid))
            return false;
        if (company == null) {
            if (other.company != null)
                return false;
        }
        else if (!company.equals(other.company))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.videogameid == null) ? 0 : this.videogameid.hashCode());
        result = prime * result + ((this.mediaid == null) ? 0 : this.mediaid.hashCode());
        result = prime * result + ((this.company == null) ? 0 : this.company.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Videogames (");

        sb.append(videogameid);
        sb.append(", ").append(mediaid);
        sb.append(", ").append(company);

        sb.append(")");
        return sb.toString();
    }
}
