/*
 * This file is generated by jOOQ.
 */
package src.main.java.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import src.main.java.model.tables.Admins;
import src.main.java.model.tables.Books;
import src.main.java.model.tables.Episodes;
import src.main.java.model.tables.Genres;
import src.main.java.model.tables.Listmedia;
import src.main.java.model.tables.Lists;
import src.main.java.model.tables.Media;
import src.main.java.model.tables.Mediagenres;
import src.main.java.model.tables.Movies;
import src.main.java.model.tables.Normals;
import src.main.java.model.tables.People;
import src.main.java.model.tables.Peoplebooks;
import src.main.java.model.tables.Peopleepisodes;
import src.main.java.model.tables.Peoplemovies;
import src.main.java.model.tables.Peoplevideogames;
import src.main.java.model.tables.Platforms;
import src.main.java.model.tables.Reports;
import src.main.java.model.tables.Reviewlikes;
import src.main.java.model.tables.Reviews;
import src.main.java.model.tables.Seasons;
import src.main.java.model.tables.Series;
import src.main.java.model.tables.Trackers;
import src.main.java.model.tables.Users;
import src.main.java.model.tables.Videogameplatforms;
import src.main.java.model.tables.Videogames;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Harmony extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>harmony</code>
     */
    public static final Harmony HARMONY = new Harmony();

    /**
     * The table <code>harmony.admins</code>.
     */
    public final Admins ADMINS = Admins.ADMINS;

    /**
     * The table <code>harmony.books</code>.
     */
    public final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>harmony.episodes</code>.
     */
    public final Episodes EPISODES = Episodes.EPISODES;

    /**
     * The table <code>harmony.genres</code>.
     */
    public final Genres GENRES = Genres.GENRES;

    /**
     * The table <code>harmony.listmedia</code>.
     */
    public final Listmedia LISTMEDIA = Listmedia.LISTMEDIA;

    /**
     * The table <code>harmony.lists</code>.
     */
    public final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>harmony.media</code>.
     */
    public final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>harmony.mediaGenres</code>.
     */
    public final Mediagenres MEDIAGENRES = Mediagenres.MEDIAGENRES;

    /**
     * The table <code>harmony.movies</code>.
     */
    public final Movies MOVIES = Movies.MOVIES;

    /**
     * The table <code>harmony.normals</code>.
     */
    public final Normals NORMALS = Normals.NORMALS;

    /**
     * The table <code>harmony.people</code>.
     */
    public final People PEOPLE = People.PEOPLE;

    /**
     * The table <code>harmony.peopleBooks</code>.
     */
    public final Peoplebooks PEOPLEBOOKS = Peoplebooks.PEOPLEBOOKS;

    /**
     * The table <code>harmony.peopleEpisodes</code>.
     */
    public final Peopleepisodes PEOPLEEPISODES = Peopleepisodes.PEOPLEEPISODES;

    /**
     * The table <code>harmony.peopleMovies</code>.
     */
    public final Peoplemovies PEOPLEMOVIES = Peoplemovies.PEOPLEMOVIES;

    /**
     * The table <code>harmony.peopleVideogames</code>.
     */
    public final Peoplevideogames PEOPLEVIDEOGAMES = Peoplevideogames.PEOPLEVIDEOGAMES;

    /**
     * The table <code>harmony.platforms</code>.
     */
    public final Platforms PLATFORMS = Platforms.PLATFORMS;

    /**
     * The table <code>harmony.reports</code>.
     */
    public final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>harmony.reviewlikes</code>.
     */
    public final Reviewlikes REVIEWLIKES = Reviewlikes.REVIEWLIKES;

    /**
     * The table <code>harmony.reviews</code>.
     */
    public final Reviews REVIEWS = Reviews.REVIEWS;

    /**
     * The table <code>harmony.seasons</code>.
     */
    public final Seasons SEASONS = Seasons.SEASONS;

    /**
     * The table <code>harmony.series</code>.
     */
    public final Series SERIES = Series.SERIES;

    /**
     * The table <code>harmony.trackers</code>.
     */
    public final Trackers TRACKERS = Trackers.TRACKERS;

    /**
     * The table <code>harmony.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>harmony.videogameplatforms</code>.
     */
    public final Videogameplatforms VIDEOGAMEPLATFORMS = Videogameplatforms.VIDEOGAMEPLATFORMS;

    /**
     * The table <code>harmony.videogames</code>.
     */
    public final Videogames VIDEOGAMES = Videogames.VIDEOGAMES;

    /**
     * No further instances allowed
     */
    private Harmony() {
        super("harmony", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Admins.ADMINS,
            Books.BOOKS,
            Episodes.EPISODES,
            Genres.GENRES,
            Listmedia.LISTMEDIA,
            Lists.LISTS,
            Media.MEDIA,
            Mediagenres.MEDIAGENRES,
            Movies.MOVIES,
            Normals.NORMALS,
            People.PEOPLE,
            Peoplebooks.PEOPLEBOOKS,
            Peopleepisodes.PEOPLEEPISODES,
            Peoplemovies.PEOPLEMOVIES,
            Peoplevideogames.PEOPLEVIDEOGAMES,
            Platforms.PLATFORMS,
            Reports.REPORTS,
            Reviewlikes.REVIEWLIKES,
            Reviews.REVIEWS,
            Seasons.SEASONS,
            Series.SERIES,
            Trackers.TRACKERS,
            Users.USERS,
            Videogameplatforms.VIDEOGAMEPLATFORMS,
            Videogames.VIDEOGAMES);
    }
}
