/*
 * This file is generated by jOOQ.
 */
package src.main.java.model;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import src.main.java.model.tables.Listmedia;
import src.main.java.model.tables.Mediagenres;
import src.main.java.model.tables.Peoplebooks;
import src.main.java.model.tables.Peopleepisodes;
import src.main.java.model.tables.Peoplemovies;
import src.main.java.model.tables.Peoplevideogames;
import src.main.java.model.tables.Reports;
import src.main.java.model.tables.Reviewlikes;
import src.main.java.model.tables.Reviews;
import src.main.java.model.tables.Trackers;
import src.main.java.model.tables.Videogameplatforms;


/**
 * A class modelling indexes of tables in harmony.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MEDIAGENRES_GENREID = Internal.createIndex(DSL.name("genreid"), Mediagenres.MEDIAGENRES, new OrderField[] { Mediagenres.MEDIAGENRES.GENREID }, false);
    public static final Index LISTMEDIA_MEDIAID = Internal.createIndex(DSL.name("mediaid"), Listmedia.LISTMEDIA, new OrderField[] { Listmedia.LISTMEDIA.MEDIAID }, false);
    public static final Index REVIEWS_MEDIAID = Internal.createIndex(DSL.name("mediaid"), Reviews.REVIEWS, new OrderField[] { Reviews.REVIEWS.MEDIAID }, false);
    public static final Index TRACKERS_MEDIAID = Internal.createIndex(DSL.name("mediaid"), Trackers.TRACKERS, new OrderField[] { Trackers.TRACKERS.MEDIAID }, false);
    public static final Index PEOPLEBOOKS_PERSONID = Internal.createIndex(DSL.name("personid"), Peoplebooks.PEOPLEBOOKS, new OrderField[] { Peoplebooks.PEOPLEBOOKS.PERSONID }, false);
    public static final Index PEOPLEEPISODES_PERSONID = Internal.createIndex(DSL.name("personid"), Peopleepisodes.PEOPLEEPISODES, new OrderField[] { Peopleepisodes.PEOPLEEPISODES.PERSONID }, false);
    public static final Index PEOPLEMOVIES_PERSONID = Internal.createIndex(DSL.name("personid"), Peoplemovies.PEOPLEMOVIES, new OrderField[] { Peoplemovies.PEOPLEMOVIES.PERSONID }, false);
    public static final Index PEOPLEVIDEOGAMES_PERSONID = Internal.createIndex(DSL.name("personid"), Peoplevideogames.PEOPLEVIDEOGAMES, new OrderField[] { Peoplevideogames.PEOPLEVIDEOGAMES.PERSONID }, false);
    public static final Index VIDEOGAMEPLATFORMS_PLATFORMID = Internal.createIndex(DSL.name("platformid"), Videogameplatforms.VIDEOGAMEPLATFORMS, new OrderField[] { Videogameplatforms.VIDEOGAMEPLATFORMS.PLATFORMID }, false);
    public static final Index REPORTS_REVIEWID = Internal.createIndex(DSL.name("reviewid"), Reports.REPORTS, new OrderField[] { Reports.REPORTS.REVIEWID }, false);
    public static final Index REVIEWLIKES_REVIEWID = Internal.createIndex(DSL.name("reviewid"), Reviewlikes.REVIEWLIKES, new OrderField[] { Reviewlikes.REVIEWLIKES.REVIEWID }, false);
    public static final Index TRACKERS_USERID = Internal.createIndex(DSL.name("userid"), Trackers.TRACKERS, new OrderField[] { Trackers.TRACKERS.USERID }, false);
    public static final Index REPORTS_USERIDREPORTER = Internal.createIndex(DSL.name("useridreporter"), Reports.REPORTS, new OrderField[] { Reports.REPORTS.USERIDREPORTER }, false);
}
