/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.model.tables.Episodes;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EpisodesRecord extends UpdatableRecordImpl<EpisodesRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.episodes.episodeid</code>.
     */
    public EpisodesRecord setEpisodeid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.episodes.episodeid</code>.
     */
    public Integer getEpisodeid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.episodes.seasonid</code>.
     */
    public EpisodesRecord setSeasonid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.episodes.seasonid</code>.
     */
    public Integer getSeasonid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.episodes.episodeName</code>.
     */
    public EpisodesRecord setEpisodename(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.episodes.episodeName</code>.
     */
    public String getEpisodename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>harmony.episodes.episodeNo</code>.
     */
    public EpisodesRecord setEpisodeno(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.episodes.episodeNo</code>.
     */
    public Integer getEpisodeno() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Episodes.EPISODES.EPISODEID;
    }

    @Override
    public Field<Integer> field2() {
        return Episodes.EPISODES.SEASONID;
    }

    @Override
    public Field<String> field3() {
        return Episodes.EPISODES.EPISODENAME;
    }

    @Override
    public Field<Integer> field4() {
        return Episodes.EPISODES.EPISODENO;
    }

    @Override
    public Integer component1() {
        return getEpisodeid();
    }

    @Override
    public Integer component2() {
        return getSeasonid();
    }

    @Override
    public String component3() {
        return getEpisodename();
    }

    @Override
    public Integer component4() {
        return getEpisodeno();
    }

    @Override
    public Integer value1() {
        return getEpisodeid();
    }

    @Override
    public Integer value2() {
        return getSeasonid();
    }

    @Override
    public String value3() {
        return getEpisodename();
    }

    @Override
    public Integer value4() {
        return getEpisodeno();
    }

    @Override
    public EpisodesRecord value1(Integer value) {
        setEpisodeid(value);
        return this;
    }

    @Override
    public EpisodesRecord value2(Integer value) {
        setSeasonid(value);
        return this;
    }

    @Override
    public EpisodesRecord value3(String value) {
        setEpisodename(value);
        return this;
    }

    @Override
    public EpisodesRecord value4(Integer value) {
        setEpisodeno(value);
        return this;
    }

    @Override
    public EpisodesRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EpisodesRecord
     */
    public EpisodesRecord() {
        super(Episodes.EPISODES);
    }

    /**
     * Create a detached, initialised EpisodesRecord
     */
    public EpisodesRecord(Integer episodeid, Integer seasonid, String episodename, Integer episodeno) {
        super(Episodes.EPISODES);

        setEpisodeid(episodeid);
        setSeasonid(seasonid);
        setEpisodename(episodename);
        setEpisodeno(episodeno);
    }
}
