/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.model.tables.Media;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MediaRecord extends UpdatableRecordImpl<MediaRecord> implements Record7<Integer, String, LocalDate, String, String, String, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.media.mediaid</code>.
     */
    public MediaRecord setMediaid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.media.mediaid</code>.
     */
    public Integer getMediaid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.media.title</code>.
     */
    public MediaRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.media.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>harmony.media.releaseDate</code>.
     */
    public MediaRecord setReleasedate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.media.releaseDate</code>.
     */
    public LocalDate getReleasedate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>harmony.media.coverImage</code>.
     */
    public MediaRecord setCoverimage(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.media.coverImage</code>.
     */
    public String getCoverimage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>harmony.media.backgroundImage</code>.
     */
    public MediaRecord setBackgroundimage(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>harmony.media.backgroundImage</code>.
     */
    public String getBackgroundimage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>harmony.media.synopsis</code>.
     */
    public MediaRecord setSynopsis(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>harmony.media.synopsis</code>.
     */
    public String getSynopsis() {
        return (String) get(5);
    }

    /**
     * Setter for <code>harmony.media.avgRating</code>.
     */
    public MediaRecord setAvgrating(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>harmony.media.avgRating</code>.
     */
    public Double getAvgrating() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, LocalDate, String, String, String, Double> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, LocalDate, String, String, String, Double> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Media.MEDIA.MEDIAID;
    }

    @Override
    public Field<String> field2() {
        return Media.MEDIA.TITLE;
    }

    @Override
    public Field<LocalDate> field3() {
        return Media.MEDIA.RELEASEDATE;
    }

    @Override
    public Field<String> field4() {
        return Media.MEDIA.COVERIMAGE;
    }

    @Override
    public Field<String> field5() {
        return Media.MEDIA.BACKGROUNDIMAGE;
    }

    @Override
    public Field<String> field6() {
        return Media.MEDIA.SYNOPSIS;
    }

    @Override
    public Field<Double> field7() {
        return Media.MEDIA.AVGRATING;
    }

    @Override
    public Integer component1() {
        return getMediaid();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public LocalDate component3() {
        return getReleasedate();
    }

    @Override
    public String component4() {
        return getCoverimage();
    }

    @Override
    public String component5() {
        return getBackgroundimage();
    }

    @Override
    public String component6() {
        return getSynopsis();
    }

    @Override
    public Double component7() {
        return getAvgrating();
    }

    @Override
    public Integer value1() {
        return getMediaid();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public LocalDate value3() {
        return getReleasedate();
    }

    @Override
    public String value4() {
        return getCoverimage();
    }

    @Override
    public String value5() {
        return getBackgroundimage();
    }

    @Override
    public String value6() {
        return getSynopsis();
    }

    @Override
    public Double value7() {
        return getAvgrating();
    }

    @Override
    public MediaRecord value1(Integer value) {
        setMediaid(value);
        return this;
    }

    @Override
    public MediaRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public MediaRecord value3(LocalDate value) {
        setReleasedate(value);
        return this;
    }

    @Override
    public MediaRecord value4(String value) {
        setCoverimage(value);
        return this;
    }

    @Override
    public MediaRecord value5(String value) {
        setBackgroundimage(value);
        return this;
    }

    @Override
    public MediaRecord value6(String value) {
        setSynopsis(value);
        return this;
    }

    @Override
    public MediaRecord value7(Double value) {
        setAvgrating(value);
        return this;
    }

    @Override
    public MediaRecord values(Integer value1, String value2, LocalDate value3, String value4, String value5, String value6, Double value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaRecord
     */
    public MediaRecord() {
        super(Media.MEDIA);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(Integer mediaid, String title, LocalDate releasedate, String coverimage, String backgroundimage, String synopsis, Double avgrating) {
        super(Media.MEDIA);

        setMediaid(mediaid);
        setTitle(title);
        setReleasedate(releasedate);
        setCoverimage(coverimage);
        setBackgroundimage(backgroundimage);
        setSynopsis(synopsis);
        setAvgrating(avgrating);
    }
}
