/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.model.tables.Movies;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoviesRecord extends UpdatableRecordImpl<MoviesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.movies.movieid</code>.
     */
    public MoviesRecord setMovieid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.movies.movieid</code>.
     */
    public Integer getMovieid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.movies.mediaid</code>.
     */
    public MoviesRecord setMediaid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.movies.mediaid</code>.
     */
    public Integer getMediaid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Movies.MOVIES.MOVIEID;
    }

    @Override
    public Field<Integer> field2() {
        return Movies.MOVIES.MEDIAID;
    }

    @Override
    public Integer component1() {
        return getMovieid();
    }

    @Override
    public Integer component2() {
        return getMediaid();
    }

    @Override
    public Integer value1() {
        return getMovieid();
    }

    @Override
    public Integer value2() {
        return getMediaid();
    }

    @Override
    public MoviesRecord value1(Integer value) {
        setMovieid(value);
        return this;
    }

    @Override
    public MoviesRecord value2(Integer value) {
        setMediaid(value);
        return this;
    }

    @Override
    public MoviesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MoviesRecord
     */
    public MoviesRecord() {
        super(Movies.MOVIES);
    }

    /**
     * Create a detached, initialised MoviesRecord
     */
    public MoviesRecord(Integer movieid, Integer mediaid) {
        super(Movies.MOVIES);

        setMovieid(movieid);
        setMediaid(mediaid);
    }
}
