/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.model.tables.Peoplebooks;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeoplebooksRecord extends UpdatableRecordImpl<PeoplebooksRecord> implements Record5<Integer, Integer, Integer, String, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.peopleBooks.peopleBooksid</code>.
     */
    public PeoplebooksRecord setPeoplebooksid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleBooks.peopleBooksid</code>.
     */
    public Integer getPeoplebooksid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.peopleBooks.bookid</code>.
     */
    public PeoplebooksRecord setBookid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleBooks.bookid</code>.
     */
    public Integer getBookid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.peopleBooks.personid</code>.
     */
    public PeoplebooksRecord setPersonid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleBooks.personid</code>.
     */
    public Integer getPersonid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>harmony.peopleBooks.role</code>.
     */
    public PeoplebooksRecord setRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleBooks.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>harmony.peopleBooks.roletype</code>.
     */
    public PeoplebooksRecord setRoletype(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleBooks.roletype</code>.
     */
    public Byte getRoletype() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, String, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, String, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Peoplebooks.PEOPLEBOOKS.PEOPLEBOOKSID;
    }

    @Override
    public Field<Integer> field2() {
        return Peoplebooks.PEOPLEBOOKS.BOOKID;
    }

    @Override
    public Field<Integer> field3() {
        return Peoplebooks.PEOPLEBOOKS.PERSONID;
    }

    @Override
    public Field<String> field4() {
        return Peoplebooks.PEOPLEBOOKS.ROLE;
    }

    @Override
    public Field<Byte> field5() {
        return Peoplebooks.PEOPLEBOOKS.ROLETYPE;
    }

    @Override
    public Integer component1() {
        return getPeoplebooksid();
    }

    @Override
    public Integer component2() {
        return getBookid();
    }

    @Override
    public Integer component3() {
        return getPersonid();
    }

    @Override
    public String component4() {
        return getRole();
    }

    @Override
    public Byte component5() {
        return getRoletype();
    }

    @Override
    public Integer value1() {
        return getPeoplebooksid();
    }

    @Override
    public Integer value2() {
        return getBookid();
    }

    @Override
    public Integer value3() {
        return getPersonid();
    }

    @Override
    public String value4() {
        return getRole();
    }

    @Override
    public Byte value5() {
        return getRoletype();
    }

    @Override
    public PeoplebooksRecord value1(Integer value) {
        setPeoplebooksid(value);
        return this;
    }

    @Override
    public PeoplebooksRecord value2(Integer value) {
        setBookid(value);
        return this;
    }

    @Override
    public PeoplebooksRecord value3(Integer value) {
        setPersonid(value);
        return this;
    }

    @Override
    public PeoplebooksRecord value4(String value) {
        setRole(value);
        return this;
    }

    @Override
    public PeoplebooksRecord value5(Byte value) {
        setRoletype(value);
        return this;
    }

    @Override
    public PeoplebooksRecord values(Integer value1, Integer value2, Integer value3, String value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeoplebooksRecord
     */
    public PeoplebooksRecord() {
        super(Peoplebooks.PEOPLEBOOKS);
    }

    /**
     * Create a detached, initialised PeoplebooksRecord
     */
    public PeoplebooksRecord(Integer peoplebooksid, Integer bookid, Integer personid, String role, Byte roletype) {
        super(Peoplebooks.PEOPLEBOOKS);

        setPeoplebooksid(peoplebooksid);
        setBookid(bookid);
        setPersonid(personid);
        setRole(role);
        setRoletype(roletype);
    }
}
