/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.model.tables.Peoplevideogames;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeoplevideogamesRecord extends UpdatableRecordImpl<PeoplevideogamesRecord> implements Record5<Integer, Integer, Integer, String, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.peopleVideogames.peopleVideogamesid</code>.
     */
    public PeoplevideogamesRecord setPeoplevideogamesid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleVideogames.peopleVideogamesid</code>.
     */
    public Integer getPeoplevideogamesid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.peopleVideogames.videogameid</code>.
     */
    public PeoplevideogamesRecord setVideogameid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleVideogames.videogameid</code>.
     */
    public Integer getVideogameid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.peopleVideogames.personid</code>.
     */
    public PeoplevideogamesRecord setPersonid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleVideogames.personid</code>.
     */
    public Integer getPersonid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>harmony.peopleVideogames.role</code>.
     */
    public PeoplevideogamesRecord setRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleVideogames.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>harmony.peopleVideogames.roletype</code>.
     */
    public PeoplevideogamesRecord setRoletype(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>harmony.peopleVideogames.roletype</code>.
     */
    public Byte getRoletype() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, String, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, String, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Peoplevideogames.PEOPLEVIDEOGAMES.PEOPLEVIDEOGAMESID;
    }

    @Override
    public Field<Integer> field2() {
        return Peoplevideogames.PEOPLEVIDEOGAMES.VIDEOGAMEID;
    }

    @Override
    public Field<Integer> field3() {
        return Peoplevideogames.PEOPLEVIDEOGAMES.PERSONID;
    }

    @Override
    public Field<String> field4() {
        return Peoplevideogames.PEOPLEVIDEOGAMES.ROLE;
    }

    @Override
    public Field<Byte> field5() {
        return Peoplevideogames.PEOPLEVIDEOGAMES.ROLETYPE;
    }

    @Override
    public Integer component1() {
        return getPeoplevideogamesid();
    }

    @Override
    public Integer component2() {
        return getVideogameid();
    }

    @Override
    public Integer component3() {
        return getPersonid();
    }

    @Override
    public String component4() {
        return getRole();
    }

    @Override
    public Byte component5() {
        return getRoletype();
    }

    @Override
    public Integer value1() {
        return getPeoplevideogamesid();
    }

    @Override
    public Integer value2() {
        return getVideogameid();
    }

    @Override
    public Integer value3() {
        return getPersonid();
    }

    @Override
    public String value4() {
        return getRole();
    }

    @Override
    public Byte value5() {
        return getRoletype();
    }

    @Override
    public PeoplevideogamesRecord value1(Integer value) {
        setPeoplevideogamesid(value);
        return this;
    }

    @Override
    public PeoplevideogamesRecord value2(Integer value) {
        setVideogameid(value);
        return this;
    }

    @Override
    public PeoplevideogamesRecord value3(Integer value) {
        setPersonid(value);
        return this;
    }

    @Override
    public PeoplevideogamesRecord value4(String value) {
        setRole(value);
        return this;
    }

    @Override
    public PeoplevideogamesRecord value5(Byte value) {
        setRoletype(value);
        return this;
    }

    @Override
    public PeoplevideogamesRecord values(Integer value1, Integer value2, Integer value3, String value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeoplevideogamesRecord
     */
    public PeoplevideogamesRecord() {
        super(Peoplevideogames.PEOPLEVIDEOGAMES);
    }

    /**
     * Create a detached, initialised PeoplevideogamesRecord
     */
    public PeoplevideogamesRecord(Integer peoplevideogamesid, Integer videogameid, Integer personid, String role, Byte roletype) {
        super(Peoplevideogames.PEOPLEVIDEOGAMES);

        setPeoplevideogamesid(peoplevideogamesid);
        setVideogameid(videogameid);
        setPersonid(personid);
        setRole(role);
        setRoletype(roletype);
    }
}
