/*
 * This file is generated by jOOQ.
 */
package src.main.java.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.model.tables.Trackers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackersRecord extends UpdatableRecordImpl<TrackersRecord> implements Record6<Integer, Integer, Integer, Integer, Byte, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>harmony.trackers.trackerid</code>.
     */
    public TrackersRecord setTrackerid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.trackerid</code>.
     */
    public Integer getTrackerid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>harmony.trackers.mediaid</code>.
     */
    public TrackersRecord setMediaid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.mediaid</code>.
     */
    public Integer getMediaid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>harmony.trackers.userid</code>.
     */
    public TrackersRecord setUserid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>harmony.trackers.state</code>.
     */
    public TrackersRecord setState(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.state</code>.
     */
    public Integer getState() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>harmony.trackers.active</code>.
     */
    public TrackersRecord setActive(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.active</code>.
     */
    public Byte getActive() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>harmony.trackers.creationDate</code>.
     */
    public TrackersRecord setCreationdate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.creationDate</code>.
     */
    public LocalDateTime getCreationdate() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Integer, Byte, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, Integer, Byte, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Trackers.TRACKERS.TRACKERID;
    }

    @Override
    public Field<Integer> field2() {
        return Trackers.TRACKERS.MEDIAID;
    }

    @Override
    public Field<Integer> field3() {
        return Trackers.TRACKERS.USERID;
    }

    @Override
    public Field<Integer> field4() {
        return Trackers.TRACKERS.STATE;
    }

    @Override
    public Field<Byte> field5() {
        return Trackers.TRACKERS.ACTIVE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Trackers.TRACKERS.CREATIONDATE;
    }

    @Override
    public Integer component1() {
        return getTrackerid();
    }

    @Override
    public Integer component2() {
        return getMediaid();
    }

    @Override
    public Integer component3() {
        return getUserid();
    }

    @Override
    public Integer component4() {
        return getState();
    }

    @Override
    public Byte component5() {
        return getActive();
    }

    @Override
    public LocalDateTime component6() {
        return getCreationdate();
    }

    @Override
    public Integer value1() {
        return getTrackerid();
    }

    @Override
    public Integer value2() {
        return getMediaid();
    }

    @Override
    public Integer value3() {
        return getUserid();
    }

    @Override
    public Integer value4() {
        return getState();
    }

    @Override
    public Byte value5() {
        return getActive();
    }

    @Override
    public LocalDateTime value6() {
        return getCreationdate();
    }

    @Override
    public TrackersRecord value1(Integer value) {
        setTrackerid(value);
        return this;
    }

    @Override
    public TrackersRecord value2(Integer value) {
        setMediaid(value);
        return this;
    }

    @Override
    public TrackersRecord value3(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public TrackersRecord value4(Integer value) {
        setState(value);
        return this;
    }

    @Override
    public TrackersRecord value5(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public TrackersRecord value6(LocalDateTime value) {
        setCreationdate(value);
        return this;
    }

    @Override
    public TrackersRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Byte value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackersRecord
     */
    public TrackersRecord() {
        super(Trackers.TRACKERS);
    }

    /**
     * Create a detached, initialised TrackersRecord
     */
    public TrackersRecord(Integer trackerid, Integer mediaid, Integer userid, Integer state, Byte active, LocalDateTime creationdate) {
        super(Trackers.TRACKERS);

        setTrackerid(trackerid);
        setMediaid(mediaid);
        setUserid(userid);
        setState(state);
        setActive(active);
        setCreationdate(creationdate);
    }
}
