/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Peoplemovies implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer peoplemoviesid;
    private Integer movieid;
    private Integer personid;
    private String  role;
    private Byte    roletype;

    public Peoplemovies() {}

    public Peoplemovies(Peoplemovies value) {
        this.peoplemoviesid = value.peoplemoviesid;
        this.movieid = value.movieid;
        this.personid = value.personid;
        this.role = value.role;
        this.roletype = value.roletype;
    }

    public Peoplemovies(
        Integer peoplemoviesid,
        Integer movieid,
        Integer personid,
        String  role,
        Byte    roletype
    ) {
        this.peoplemoviesid = peoplemoviesid;
        this.movieid = movieid;
        this.personid = personid;
        this.role = role;
        this.roletype = roletype;
    }

    /**
     * Getter for <code>harmony.peopleMovies.peopleMoviesid</code>.
     */
    public Integer getPeoplemoviesid() {
        return this.peoplemoviesid;
    }

    /**
     * Setter for <code>harmony.peopleMovies.peopleMoviesid</code>.
     */
    public Peoplemovies setPeoplemoviesid(Integer peoplemoviesid) {
        this.peoplemoviesid = peoplemoviesid;
        return this;
    }

    /**
     * Getter for <code>harmony.peopleMovies.movieid</code>.
     */
    public Integer getMovieid() {
        return this.movieid;
    }

    /**
     * Setter for <code>harmony.peopleMovies.movieid</code>.
     */
    public Peoplemovies setMovieid(Integer movieid) {
        this.movieid = movieid;
        return this;
    }

    /**
     * Getter for <code>harmony.peopleMovies.personid</code>.
     */
    public Integer getPersonid() {
        return this.personid;
    }

    /**
     * Setter for <code>harmony.peopleMovies.personid</code>.
     */
    public Peoplemovies setPersonid(Integer personid) {
        this.personid = personid;
        return this;
    }

    /**
     * Getter for <code>harmony.peopleMovies.role</code>.
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>harmony.peopleMovies.role</code>.
     */
    public Peoplemovies setRole(String role) {
        this.role = role;
        return this;
    }

    /**
     * Getter for <code>harmony.peopleMovies.roletype</code>.
     */
    public Byte getRoletype() {
        return this.roletype;
    }

    /**
     * Setter for <code>harmony.peopleMovies.roletype</code>.
     */
    public Peoplemovies setRoletype(Byte roletype) {
        this.roletype = roletype;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Peoplemovies other = (Peoplemovies) obj;
        if (peoplemoviesid == null) {
            if (other.peoplemoviesid != null)
                return false;
        }
        else if (!peoplemoviesid.equals(other.peoplemoviesid))
            return false;
        if (movieid == null) {
            if (other.movieid != null)
                return false;
        }
        else if (!movieid.equals(other.movieid))
            return false;
        if (personid == null) {
            if (other.personid != null)
                return false;
        }
        else if (!personid.equals(other.personid))
            return false;
        if (role == null) {
            if (other.role != null)
                return false;
        }
        else if (!role.equals(other.role))
            return false;
        if (roletype == null) {
            if (other.roletype != null)
                return false;
        }
        else if (!roletype.equals(other.roletype))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.peoplemoviesid == null) ? 0 : this.peoplemoviesid.hashCode());
        result = prime * result + ((this.movieid == null) ? 0 : this.movieid.hashCode());
        result = prime * result + ((this.personid == null) ? 0 : this.personid.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.roletype == null) ? 0 : this.roletype.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Peoplemovies (");

        sb.append(peoplemoviesid);
        sb.append(", ").append(movieid);
        sb.append(", ").append(personid);
        sb.append(", ").append(role);
        sb.append(", ").append(roletype);

        sb.append(")");
        return sb.toString();
    }
}
