/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trackers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       trackerid;
    private Integer       mediaid;
    private Integer       userid;
    private Integer       state;
    private LocalDateTime datetime;

    public Trackers() {}

    public Trackers(Trackers value) {
        this.trackerid = value.trackerid;
        this.mediaid = value.mediaid;
        this.userid = value.userid;
        this.state = value.state;
        this.datetime = value.datetime;
    }

    public Trackers(
        Integer       trackerid,
        Integer       mediaid,
        Integer       userid,
        Integer       state,
        LocalDateTime datetime
    ) {
        this.trackerid = trackerid;
        this.mediaid = mediaid;
        this.userid = userid;
        this.state = state;
        this.datetime = datetime;
    }

    /**
     * Getter for <code>harmony.trackers.trackerid</code>.
     */
    public Integer getTrackerid() {
        return this.trackerid;
    }

    /**
     * Setter for <code>harmony.trackers.trackerid</code>.
     */
    public Trackers setTrackerid(Integer trackerid) {
        this.trackerid = trackerid;
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.mediaid</code>.
     */
    public Integer getMediaid() {
        return this.mediaid;
    }

    /**
     * Setter for <code>harmony.trackers.mediaid</code>.
     */
    public Trackers setMediaid(Integer mediaid) {
        this.mediaid = mediaid;
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.userid</code>.
     */
    public Integer getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>harmony.trackers.userid</code>.
     */
    public Trackers setUserid(Integer userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.state</code>.
     */
    public Integer getState() {
        return this.state;
    }

    /**
     * Setter for <code>harmony.trackers.state</code>.
     */
    public Trackers setState(Integer state) {
        this.state = state;
        return this;
    }

    /**
     * Getter for <code>harmony.trackers.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return this.datetime;
    }

    /**
     * Setter for <code>harmony.trackers.datetime</code>.
     */
    public Trackers setDatetime(LocalDateTime datetime) {
        this.datetime = datetime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Trackers other = (Trackers) obj;
        if (trackerid == null) {
            if (other.trackerid != null)
                return false;
        }
        else if (!trackerid.equals(other.trackerid))
            return false;
        if (mediaid == null) {
            if (other.mediaid != null)
                return false;
        }
        else if (!mediaid.equals(other.mediaid))
            return false;
        if (userid == null) {
            if (other.userid != null)
                return false;
        }
        else if (!userid.equals(other.userid))
            return false;
        if (state == null) {
            if (other.state != null)
                return false;
        }
        else if (!state.equals(other.state))
            return false;
        if (datetime == null) {
            if (other.datetime != null)
                return false;
        }
        else if (!datetime.equals(other.datetime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trackerid == null) ? 0 : this.trackerid.hashCode());
        result = prime * result + ((this.mediaid == null) ? 0 : this.mediaid.hashCode());
        result = prime * result + ((this.userid == null) ? 0 : this.userid.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.datetime == null) ? 0 : this.datetime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Trackers (");

        sb.append(trackerid);
        sb.append(", ").append(mediaid);
        sb.append(", ").append(userid);
        sb.append(", ").append(state);
        sb.append(", ").append(datetime);

        sb.append(")");
        return sb.toString();
    }
}
