/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import src.main.java.harmony.Harmony;
import src.main.java.harmony.Keys;
import src.main.java.harmony.tables.records.SeasonsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Seasons extends TableImpl<SeasonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>harmony.seasons</code>
     */
    public static final Seasons SEASONS = new Seasons();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeasonsRecord> getRecordType() {
        return SeasonsRecord.class;
    }

    /**
     * The column <code>harmony.seasons.seasonid</code>.
     */
    public final TableField<SeasonsRecord, Integer> SEASONID = createField(DSL.name("seasonid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>harmony.seasons.seriesid</code>.
     */
    public final TableField<SeasonsRecord, Integer> SERIESID = createField(DSL.name("seriesid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>harmony.seasons.seasonNo</code>.
     */
    public final TableField<SeasonsRecord, Integer> SEASONNO = createField(DSL.name("seasonNo"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>harmony.seasons.noEpisodes</code>.
     */
    public final TableField<SeasonsRecord, Integer> NOEPISODES = createField(DSL.name("noEpisodes"), SQLDataType.INTEGER.nullable(false), this, "");

    private Seasons(Name alias, Table<SeasonsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Seasons(Name alias, Table<SeasonsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>harmony.seasons</code> table reference
     */
    public Seasons(String alias) {
        this(DSL.name(alias), SEASONS);
    }

    /**
     * Create an aliased <code>harmony.seasons</code> table reference
     */
    public Seasons(Name alias) {
        this(alias, SEASONS);
    }

    /**
     * Create a <code>harmony.seasons</code> table reference
     */
    public Seasons() {
        this(DSL.name("seasons"), null);
    }

    public <O extends Record> Seasons(Table<O> child, ForeignKey<O, SeasonsRecord> key) {
        super(child, key, SEASONS);
    }

    @Override
    public Schema getSchema() {
        return Harmony.HARMONY;
    }

    @Override
    public Identity<SeasonsRecord, Integer> getIdentity() {
        return (Identity<SeasonsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SeasonsRecord> getPrimaryKey() {
        return Keys.KEY_SEASONS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SeasonsRecord>> getKeys() {
        return Arrays.<UniqueKey<SeasonsRecord>>asList(Keys.KEY_SEASONS_PRIMARY, Keys.KEY_SEASONS_SEASONID, Keys.KEY_SEASONS_DUPLICATEDENTRY_SEASONS);
    }

    @Override
    public List<ForeignKey<SeasonsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SeasonsRecord, ?>>asList(Keys.SEASONS_IBFK_1);
    }

    private transient Series _series;

    public Series series() {
        if (_series == null)
            _series = new Series(this, Keys.SEASONS_IBFK_1);

        return _series;
    }

    @Override
    public Seasons as(String alias) {
        return new Seasons(DSL.name(alias), this);
    }

    @Override
    public Seasons as(Name alias) {
        return new Seasons(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Seasons rename(String name) {
        return new Seasons(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Seasons rename(Name name) {
        return new Seasons(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
