/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.harmony.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newgenre extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newGenre.name</code>.
     */
    public static final Parameter<String> NAME = Internal.createParameter("name", SQLDataType.VARCHAR(50), false, false);

    /**
     * Create a new routine call instance
     */
    public Newgenre() {
        super("newGenre", Harmony.HARMONY);

        addInParameter(NAME);
    }

    /**
     * Set the <code>name</code> parameter IN value to the routine
     */
    public void setName_(String value) {
        setValue(NAME, value);
    }
}
