/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.harmony.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newlist extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newList.user</code>.
     */
    public static final Parameter<Integer> USER = Internal.createParameter("user", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newList.listName</code>.
     */
    public static final Parameter<String> LISTNAME = Internal.createParameter("listName", SQLDataType.VARCHAR(60), false, false);

    /**
     * The parameter <code>harmony.newList.icon</code>.
     */
    public static final Parameter<String> ICON = Internal.createParameter("icon", SQLDataType.VARCHAR(1), false, false);

    /**
     * Create a new routine call instance
     */
    public Newlist() {
        super("newList", Harmony.HARMONY);

        addInParameter(USER);
        addInParameter(LISTNAME);
        addInParameter(ICON);
    }

    /**
     * Set the <code>user</code> parameter IN value to the routine
     */
    public void setUser(Integer value) {
        setValue(USER, value);
    }

    /**
     * Set the <code>listName</code> parameter IN value to the routine
     */
    public void setListname(String value) {
        setValue(LISTNAME, value);
    }

    /**
     * Set the <code>icon</code> parameter IN value to the routine
     */
    public void setIcon(String value) {
        setValue(ICON, value);
    }
}
