/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.harmony.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newplatform extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newPlatform.platformName</code>.
     */
    public static final Parameter<String> PLATFORMNAME = Internal.createParameter("platformName", SQLDataType.VARCHAR(60), false, false);

    /**
     * Create a new routine call instance
     */
    public Newplatform() {
        super("newPlatform", Harmony.HARMONY);

        addInParameter(PLATFORMNAME);
    }

    /**
     * Set the <code>platformName</code> parameter IN value to the routine
     */
    public void setPlatformname(String value) {
        setValue(PLATFORMNAME, value);
    }
}
