/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.harmony.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newreport extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.newReport.userReporter</code>.
     */
    public static final Parameter<Integer> USERREPORTER = Internal.createParameter("userReporter", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newReport.userReported</code>.
     */
    public static final Parameter<Integer> USERREPORTED = Internal.createParameter("userReported", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newReport.review</code>.
     */
    public static final Parameter<Integer> REVIEW = Internal.createParameter("review", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.newReport.reason</code>.
     */
    public static final Parameter<String> REASON = Internal.createParameter("reason", SQLDataType.VARCHAR(120), false, false);

    /**
     * Create a new routine call instance
     */
    public Newreport() {
        super("newReport", Harmony.HARMONY);

        addInParameter(USERREPORTER);
        addInParameter(USERREPORTED);
        addInParameter(REVIEW);
        addInParameter(REASON);
    }

    /**
     * Set the <code>userReporter</code> parameter IN value to the routine
     */
    public void setUserreporter(Integer value) {
        setValue(USERREPORTER, value);
    }

    /**
     * Set the <code>userReported</code> parameter IN value to the routine
     */
    public void setUserreported(Integer value) {
        setValue(USERREPORTED, value);
    }

    /**
     * Set the <code>review</code> parameter IN value to the routine
     */
    public void setReview(Integer value) {
        setValue(REVIEW, value);
    }

    /**
     * Set the <code>reason</code> parameter IN value to the routine
     */
    public void setReason(String value) {
        setValue(REASON, value);
    }
}
