/*
 * This file is generated by jOOQ.
 */
package src.main.java.harmony.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import src.main.java.harmony.Harmony;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Updatereview extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>harmony.updateReview.id</code>.
     */
    public static final Parameter<Integer> ID = Internal.createParameter("id", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>harmony.updateReview.newreview</code>.
     */
    public static final Parameter<String> NEWREVIEW = Internal.createParameter("newreview", SQLDataType.VARCHAR(2800), false, false);

    /**
     * The parameter <code>harmony.updateReview.newrating</code>.
     */
    public static final Parameter<Double> NEWRATING = Internal.createParameter("newrating", SQLDataType.FLOAT, false, false);

    /**
     * Create a new routine call instance
     */
    public Updatereview() {
        super("updateReview", Harmony.HARMONY);

        addInParameter(ID);
        addInParameter(NEWREVIEW);
        addInParameter(NEWRATING);
    }

    /**
     * Set the <code>id</code> parameter IN value to the routine
     */
    public void setId(Integer value) {
        setValue(ID, value);
    }

    /**
     * Set the <code>newreview</code> parameter IN value to the routine
     */
    public void setNewreview(String value) {
        setValue(NEWREVIEW, value);
    }

    /**
     * Set the <code>newrating</code> parameter IN value to the routine
     */
    public void setNewrating(Double value) {
        setValue(NEWRATING, value);
    }
}
